### ISSUE TITLE
Killing the app with SIGTERM left my windows manager stuck small

### ISSUE THREAD

**Issue by nh2** [splitbrain/clipscreen#3]
I did a `killall clipscreen` which resulted in this:

![image](https://github.com/user-attachments/assets/b646851e-b828-49a8-8360-459bdfacd39c)

Now `clipscreen` terminated and all my i3 workspaces are now clipped to the region, and not restored as happens with normal SIGINT termination (`Ctrl+C`).

Would be cool to

* [ ] Also handle SIGTERM
* [ ] Mention in the README what can be done in such situation (where `clipscreen` is killed and cannot run its cleanup code)

**Comment by nh2** [comment]
Also, in this state, all subsequent invocaitons of `clipscreen` fail:

`./clipscreen 50 50 0 0`

```
Added virtual monitor
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  43 ()
  Value in failed request:  0x353
  Serial number of failed request:  13
  Current serial number in output stream:  16
```

**Comment by splitbrain** [comment]
to manually delete the virtual monitor use

`xrandr --delmonitor clipscreen`

I will look into preventing the issue.

**Comment by splitbrain** [comment]
SIGTERM is now handled as well and should a monitor remain anyway, it is deleted before a new one is created.
